# Generated by Django 5.2.14 on 2026-05-20 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_min_range', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_max_range', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_required', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('lab_test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtestcategory')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test_value', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.appointment')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.labtest')),
            ],
        ),
    ]
